// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"
)

const getProgramBySlug = `-- name: GetProgramBySlug :one
select id, slug, name, description
from program
where slug = $1
`

func (q *Queries) GetProgramBySlug(ctx context.Context, slug string) (Program, error) {
	row := q.db.QueryRow(ctx, getProgramBySlug, slug)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
select id, kind, title, description
from session
where id = $1
`

func (q *Queries) GetSession(ctx context.Context, id int64) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const listProgramSessions = `-- name: ListProgramSessions :many
select ps.position, s.id, s.kind, s.title
from program_session ps
join session s on s.id = ps.session_id
where ps.program_id = $1
order by ps.position
`

type ListProgramSessionsRow struct {
	Position int16
	ID       int64
	Kind     SessionKind
	Title    string
}

// Las sesiones de un programa, en orden.
func (q *Queries) ListProgramSessions(ctx context.Context, programID int64) ([]ListProgramSessionsRow, error) {
	rows, err := q.db.Query(ctx, listProgramSessions, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProgramSessionsRow
	for rows.Next() {
		var i ListProgramSessionsRow
		if err := rows.Scan(
			&i.Position,
			&i.ID,
			&i.Kind,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrograms = `-- name: ListPrograms :many

select p.id, p.slug, p.name, p.description,
       count(ps.session_id) as session_count
from program p
left join program_session ps on ps.program_id = p.id
group by p.id
order by p.id
`

type ListProgramsRow struct {
	ID           int64
	Slug         string
	Name         string
	Description  *string
	SessionCount int64
}

// Consultas de lectura del catálogo (programas y sesiones).
//
// Cada consulta lleva un comentario "-- name: <Función> <:one|:many>" que sqlc usa
// para generar una función Go: :one devuelve una fila (o pgx.ErrNoRows si no hay),
// :many devuelve un slice. Los parámetros posicionales ($1, $2...) pasan a ser
// argumentos de la función, con el tipo de la columna con la que se comparan.
// Todos los programas, con la cantidad de sesiones de cada uno.
func (q *Queries) ListPrograms(ctx context.Context) ([]ListProgramsRow, error) {
	rows, err := q.db.Query(ctx, listPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProgramsRow
	for rows.Next() {
		var i ListProgramsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.SessionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionItems = `-- name: ListSessionItems :many
select b.position   as block_position,
       b.type       as block_type,
       b.time_cap_s,
       i.round,
       i.position,
       i.kind,
       i.side,
       i.duration_s,
       i.reps,
       e.slug       as exercise_slug,
       e.name       as exercise_name
from block b
join block_item i     on i.block_id = b.id
left join exercise e  on e.id = i.exercise_id
where b.session_id = $1
order by b.position, i.round, i.position
`

type ListSessionItemsRow struct {
	BlockPosition int16
	BlockType     BlockType
	TimeCapS      *int32
	Round         int16
	Position      int16
	Kind          ItemKind
	Side          *Side
	DurationS     *int32
	Reps          *int16
	ExerciseSlug  *string
	ExerciseName  *string
}

// Todos los ítems de una sesión en orden de ejecución, una fila por ítem con los
// datos de su bloque repetidos: el código Go los agrupa en bloques. Es una sola
// consulta en vez de una por bloque (el problema "N+1" de JPA).
// El left join es porque los descansos no tienen ejercicio.
func (q *Queries) ListSessionItems(ctx context.Context, sessionID int64) ([]ListSessionItemsRow, error) {
	rows, err := q.db.Query(ctx, listSessionItems, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionItemsRow
	for rows.Next() {
		var i ListSessionItemsRow
		if err := rows.Scan(
			&i.BlockPosition,
			&i.BlockType,
			&i.TimeCapS,
			&i.Round,
			&i.Position,
			&i.Kind,
			&i.Side,
			&i.DurationS,
			&i.Reps,
			&i.ExerciseSlug,
			&i.ExerciseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
