// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateWorkoutAmraps implements pgx.CopyFromSource.
type iteratorForCreateWorkoutAmraps struct {
	rows                 []CreateWorkoutAmrapsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateWorkoutAmraps) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateWorkoutAmraps) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].WorkoutID,
		r.rows[0].BlockPosition,
		r.rows[0].Rounds,
	}, nil
}

func (r iteratorForCreateWorkoutAmraps) Err() error {
	return nil
}

func (q *Queries) CreateWorkoutAmraps(ctx context.Context, arg []CreateWorkoutAmrapsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"workout_amrap"}, []string{"workout_id", "block_position", "rounds"}, &iteratorForCreateWorkoutAmraps{rows: arg})
}

// iteratorForCreateWorkoutItems implements pgx.CopyFromSource.
type iteratorForCreateWorkoutItems struct {
	rows                 []CreateWorkoutItemsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateWorkoutItems) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateWorkoutItems) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].WorkoutID,
		r.rows[0].BlockItemID,
		r.rows[0].Reps,
		r.rows[0].DurationS,
	}, nil
}

func (r iteratorForCreateWorkoutItems) Err() error {
	return nil
}

// Inserta muchas filas de una con el protocolo COPY de Postgres: mucho más
// rápido que un INSERT por fila (el equivalente a un batch de JDBC).
func (q *Queries) CreateWorkoutItems(ctx context.Context, arg []CreateWorkoutItemsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"workout_item"}, []string{"workout_id", "block_item_id", "reps", "duration_s"}, &iteratorForCreateWorkoutItems{rows: arg})
}
