// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type BlockType string

const (
	BlockTypeRounds         BlockType = "rounds"
	BlockTypeRoundsWithRest BlockType = "rounds_with_rest"
	BlockTypeTabata         BlockType = "tabata"
	BlockTypeSuperset       BlockType = "superset"
	BlockTypeLadder         BlockType = "ladder"
	BlockTypeAmrap          BlockType = "amrap"
)

func (e *BlockType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BlockType(s)
	case string:
		*e = BlockType(s)
	default:
		return fmt.Errorf("unsupported scan type for BlockType: %T", src)
	}
	return nil
}

type NullBlockType struct {
	BlockType BlockType
	Valid     bool // Valid is true if BlockType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBlockType) Scan(value interface{}) error {
	if value == nil {
		ns.BlockType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BlockType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBlockType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BlockType), nil
}

type ItemKind string

const (
	ItemKindExercise ItemKind = "exercise"
	ItemKindRest     ItemKind = "rest"
)

func (e *ItemKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemKind(s)
	case string:
		*e = ItemKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemKind: %T", src)
	}
	return nil
}

type NullItemKind struct {
	ItemKind ItemKind
	Valid    bool // Valid is true if ItemKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemKind) Scan(value interface{}) error {
	if value == nil {
		ns.ItemKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemKind), nil
}

type SessionKind string

const (
	SessionKindWorkout  SessionKind = "workout"
	SessionKindWarmup   SessionKind = "warmup"
	SessionKindMobility SessionKind = "mobility"
	SessionKindCooldown SessionKind = "cooldown"
)

func (e *SessionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionKind(s)
	case string:
		*e = SessionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionKind: %T", src)
	}
	return nil
}

type NullSessionKind struct {
	SessionKind SessionKind
	Valid       bool // Valid is true if SessionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionKind) Scan(value interface{}) error {
	if value == nil {
		ns.SessionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionKind), nil
}

type Side string

const (
	SideLeft  Side = "left"
	SideRight Side = "right"
)

func (e *Side) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Side(s)
	case string:
		*e = Side(s)
	default:
		return fmt.Errorf("unsupported scan type for Side: %T", src)
	}
	return nil
}

type NullSide struct {
	Side  Side
	Valid bool // Valid is true if Side is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSide) Scan(value interface{}) error {
	if value == nil {
		ns.Side, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Side.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSide) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Side), nil
}

type Block struct {
	ID        int64
	SessionID int64
	Position  int16
	Type      BlockType
	TimeCapS  *int32
}

type BlockItem struct {
	ID         int64
	BlockID    int64
	Round      int16
	Position   int16
	Kind       ItemKind
	ExerciseID *int64
	Side       *Side
	DurationS  *int32
	Reps       *int16
}

type Exercise struct {
	ID          int64
	Slug        string
	Name        string
	Unilateral  bool
	Description *string
	Met         pgtype.Numeric
}

type ExerciseJoint struct {
	ExerciseID int64
	JointID    int16
}

type ExerciseMuscle struct {
	ExerciseID int64
	MuscleID   int16
}

type ExerciseProgression struct {
	EasierID int64
	HarderID int64
}

type ExerciseVideo struct {
	ExerciseID int64
	Side       *Side
	Url        string
}

type Joint struct {
	ID   int16
	Slug string
	Name string
}

type Muscle struct {
	ID   int16
	Slug string
	Name string
}

type Program struct {
	ID          int64
	Slug        string
	Name        string
	Description *string
}

type ProgramReset struct {
	UserID    string
	ProgramID int64
	ResetAt   time.Time
}

type ProgramSession struct {
	ProgramID int64
	Position  int16
	SessionID int64
}

type Session struct {
	ID          int64
	Kind        SessionKind
	Title       string
	Description *string
}

type Workout struct {
	ID         int64
	UserID     string
	SessionID  int64
	StartedAt  time.Time
	FinishedAt time.Time
	LocalDate  time.Time
	ClientID   *string
}

type WorkoutAmrap struct {
	WorkoutID     int64
	BlockPosition int16
	Rounds        int16
}

type WorkoutItem struct {
	WorkoutID   int64
	BlockItemID int64
	Reps        *int16
	DurationS   *int32
}
