// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: training.sql

package db

import (
	"context"
	"time"
)

const bestResults = `-- name: BestResults :many
select wi.exercise_id,
       coalesce(max(wi.reps), 0)::int       as best_reps,
       coalesce(max(wi.duration_s), 0)::int as best_duration_s
from workout_item wi
join workout w on w.id = wi.workout_id
where w.user_id = $1
  and wi.exercise_id = any($2::bigint[])
group by wi.exercise_id
`

type BestResultsParams struct {
	UserID      string
	ExerciseIds []int64
}

type BestResultsRow struct {
	ExerciseID    int64
	BestReps      int32
	BestDurationS int32
}

// Las mejores marcas previas del usuario en estos ejercicios (0 = sin marca).
// coalesce porque max() de ninguna fila es null. Cuenta el ejercicio que se
// hizo (wi.exercise_id), no el del bloque: pudo haberse cambiado.
func (q *Queries) BestResults(ctx context.Context, arg BestResultsParams) ([]BestResultsRow, error) {
	rows, err := q.db.Query(ctx, bestResults, arg.UserID, arg.ExerciseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BestResultsRow
	for rows.Next() {
		var i BestResultsRow
		if err := rows.Scan(&i.ExerciseID, &i.BestReps, &i.BestDurationS); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countWorkouts = `-- name: CountWorkouts :one
select count(*) from workout where user_id = $1
`

func (q *Queries) CountWorkouts(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkouts, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkout = `-- name: CreateWorkout :one
insert into workout (user_id, session_id, started_at, finished_at, local_date, client_id)
values ($1, $2, $3, $4, $5, $6)
returning id
`

type CreateWorkoutParams struct {
	UserID     string
	SessionID  int64
	StartedAt  time.Time
	FinishedAt time.Time
	LocalDate  time.Time
	ClientID   *string
}

func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (int64, error) {
	row := q.db.QueryRow(ctx, createWorkout,
		arg.UserID,
		arg.SessionID,
		arg.StartedAt,
		arg.FinishedAt,
		arg.LocalDate,
		arg.ClientID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

type CreateWorkoutAmrapsParams struct {
	WorkoutID     int64
	BlockPosition int16
	Rounds        int16
}

type CreateWorkoutItemsParams struct {
	WorkoutID   int64
	BlockItemID int64
	ExerciseID  int64
	Reps        *int16
	DurationS   *int32
}

const getWorkout = `-- name: GetWorkout :one
select w.id, w.session_id, s.title as session_title,
       coalesce(prog.slug, '')::text as program_slug,
       coalesce(prog.name, '')::text as program_name,
       w.started_at, w.finished_at, w.local_date
from workout w
join session s on s.id = w.session_id
left join lateral (
  select p.slug, p.name
  from program_session ps
  join program p on p.id = ps.program_id
  where ps.session_id = w.session_id
  order by p.id
  limit 1
) prog on true
where w.user_id = $1 and w.id = $2
`

type GetWorkoutParams struct {
	UserID string
	ID     int64
}

type GetWorkoutRow struct {
	ID           int64
	SessionID    int64
	SessionTitle string
	ProgramSlug  string
	ProgramName  string
	StartedAt    time.Time
	FinishedAt   time.Time
	LocalDate    time.Time
}

// Un workout del usuario, con la misma forma que el historial.
func (q *Queries) GetWorkout(ctx context.Context, arg GetWorkoutParams) (GetWorkoutRow, error) {
	row := q.db.QueryRow(ctx, getWorkout, arg.UserID, arg.ID)
	var i GetWorkoutRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SessionTitle,
		&i.ProgramSlug,
		&i.ProgramName,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LocalDate,
	)
	return i, err
}

const getWorkoutIDByClientID = `-- name: GetWorkoutIDByClientID :one
select id from workout where user_id = $1 and client_id = $2
`

type GetWorkoutIDByClientIDParams struct {
	UserID   string
	ClientID *string
}

// Para la idempotencia: el id del workout que el usuario ya registró con
// este client_id, si existe.
func (q *Queries) GetWorkoutIDByClientID(ctx context.Context, arg GetWorkoutIDByClientIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getWorkoutIDByClientID, arg.UserID, arg.ClientID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listCompletedSessions = `-- name: ListCompletedSessions :many
select distinct w.session_id
from workout w
join program_session ps on ps.session_id = w.session_id and ps.program_id = $1
left join program_reset r on r.program_id = $1 and r.user_id = w.user_id
where w.user_id = $2
  and (r.reset_at is null or w.finished_at > r.reset_at)
order by w.session_id
`

type ListCompletedSessionsParams struct {
	ProgramID int64
	UserID    string
}

// Los ids de las Fraguas con check de una Senda.
func (q *Queries) ListCompletedSessions(ctx context.Context, arg ListCompletedSessionsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listCompletedSessions, arg.ProgramID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var session_id int64
		if err := rows.Scan(&session_id); err != nil {
			return nil, err
		}
		items = append(items, session_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExercisesBySlug = `-- name: ListExercisesBySlug :many
select id, slug, name from exercise where slug = any($1::text[])
`

type ListExercisesBySlugRow struct {
	ID   int64
	Slug string
	Name string
}

// Los ejercicios que la app dice haber hecho en lugar de los del bloque (una
// progresión más fácil o más difícil). Los slugs que no existen no vuelven:
// así se detectan.
func (q *Queries) ListExercisesBySlug(ctx context.Context, slugs []string) ([]ListExercisesBySlugRow, error) {
	rows, err := q.db.Query(ctx, listExercisesBySlug, slugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExercisesBySlugRow
	for rows.Next() {
		var i ListExercisesBySlugRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramProgress = `-- name: ListProgramProgress :many

select p.id, p.slug, p.name,
       (select count(*) from program_session ps where ps.program_id = p.id) as total_sessions,
       (select count(distinct w.session_id)
          from workout w
          join program_session ps on ps.session_id = w.session_id and ps.program_id = p.id
         where w.user_id = $1
           and (r.reset_at is null or w.finished_at > r.reset_at)) as completed_sessions,
       r.reset_at,
       -- Con la Senda completa, la lateral no trae filas y estas columnas
       -- serían null. sqlc no puede deducir eso a través de una lateral (las
       -- tipa como no nullable y el Scan fallaría), así que se convierten a
       -- un valor centinela: 0 = no hay próxima Fragua.
       coalesce(nxt.position, 0)::smallint as next_position,
       coalesce(nxt.id, 0)::bigint         as next_session_id,
       coalesce(nxt.title, '')::text       as next_title
from program p
left join program_reset r on r.program_id = p.id and r.user_id = $1
left join lateral (
  select ps.position, s.id, s.title
  from program_session ps
  join session s on s.id = ps.session_id
  where ps.program_id = p.id
    and not exists (
      select 1 from workout w
      where w.user_id = $1 and w.session_id = ps.session_id
        and (r.reset_at is null or w.finished_at > r.reset_at)
    )
  order by ps.position
  limit 1
) nxt on true
where ($2::text is null or p.slug = $2)
order by p.id
`

type ListProgramProgressParams struct {
	UserID string
	Slug   *string
}

type ListProgramProgressRow struct {
	ID                int64
	Slug              string
	Name              string
	TotalSessions     int64
	CompletedSessions int64
	ResetAt           *time.Time
	NextPosition      int16
	NextSessionID     int64
	NextTitle         string
}

// Consultas del registro de entrenamiento. Todas filtran por user_id: un
// usuario nunca ve ni toca datos de otro, y el user_id sale siempre del token
// verificado.
//
// Regla del progreso de una Senda: una Fragua "tiene check" si el usuario la
// templó al menos una vez DESPUÉS del último reset de esa Senda (o alguna vez,
// si nunca la reseteó).
// Todas las Sendas con el progreso del usuario y la próxima Fragua sugerida
// (la primera, por posición, sin check). El "left join lateral" es una
// subconsulta que se evalúa por cada programa y puede usar sus columnas
// (p.id): como un for anidado dentro del SQL.
func (q *Queries) ListProgramProgress(ctx context.Context, arg ListProgramProgressParams) ([]ListProgramProgressRow, error) {
	rows, err := q.db.Query(ctx, listProgramProgress, arg.UserID, arg.Slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProgramProgressRow
	for rows.Next() {
		var i ListProgramProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.TotalSessions,
			&i.CompletedSessions,
			&i.ResetAt,
			&i.NextPosition,
			&i.NextSessionID,
			&i.NextTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecords = `-- name: ListRecords :many
with result as (
  select wi.exercise_id, wi.reps, wi.duration_s, w.local_date, w.finished_at
  from workout_item wi
  join workout w on w.id = wi.workout_id
  where w.user_id = $1
),
best as (
  (select distinct on (exercise_id)
          exercise_id, 'reps'::text as metric, reps::int as value, local_date
     from result
    where reps > 0
    order by exercise_id, reps desc, finished_at)
  union all
  (select distinct on (exercise_id)
          exercise_id, 'duration_s'::text, duration_s::int, local_date
     from result
    where duration_s > 0
    order by exercise_id, duration_s desc, finished_at)
)
select e.slug, e.name, b.metric, b.value, b.local_date
from best b
join exercise e on e.id = b.exercise_id
order by e.name, b.metric desc
`

type ListRecordsRow struct {
	Slug      string
	Name      string
	Metric    string
	Value     int32
	LocalDate time.Time
}

// Los Mojones: la mejor marca del usuario en cada ejercicio (juntando ambos
// lados de los unilaterales), una fila por ejercicio y métrica, con el día
// en que la logró por primera vez.
//
// Con max() + group by sale el valor, pero no el día: max() no dice de qué
// fila salió. "distinct on (exercise_id)" (propio de Postgres) se queda con
// la PRIMERA fila de cada ejercicio según el order by: ordenando por valor
// descendente y después por fecha, esa fila es la marca y el día en que se
// alcanzó (si se igualó después, cuenta la primera vez).
//
// Los "with" (CTE) son subconsultas con nombre: se leen de arriba abajo,
// como variables intermedias.
func (q *Queries) ListRecords(ctx context.Context, userID string) ([]ListRecordsRow, error) {
	rows, err := q.db.Query(ctx, listRecords, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordsRow
	for rows.Next() {
		var i ListRecordsRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.Metric,
			&i.Value,
			&i.LocalDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionAmrapPositions = `-- name: ListSessionAmrapPositions :many
select position from block where session_id = $1 and type = 'amrap'
`

// Las posiciones de los bloques AMRAP de una sesión: para validar las
// vueltas que manda la app.
func (q *Queries) ListSessionAmrapPositions(ctx context.Context, sessionID int64) ([]int16, error) {
	rows, err := q.db.Query(ctx, listSessionAmrapPositions, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int16
	for rows.Next() {
		var position int16
		if err := rows.Scan(&position); err != nil {
			return nil, err
		}
		items = append(items, position)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionItemsForWorkout = `-- name: ListSessionItemsForWorkout :many
select i.id, i.kind, i.exercise_id, e.slug as exercise_slug, e.name as exercise_name
from block_item i
join block b on b.id = i.block_id
left join exercise e on e.id = i.exercise_id
where b.session_id = $1
`

type ListSessionItemsForWorkoutRow struct {
	ID           int64
	Kind         ItemKind
	ExerciseID   *int64
	ExerciseSlug *string
	ExerciseName *string
}

// Los ítems de una sesión con su tipo y ejercicio: para validar lo que manda
// la app y para detectar Mojones.
func (q *Queries) ListSessionItemsForWorkout(ctx context.Context, sessionID int64) ([]ListSessionItemsForWorkoutRow, error) {
	rows, err := q.db.Query(ctx, listSessionItemsForWorkout, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionItemsForWorkoutRow
	for rows.Next() {
		var i ListSessionItemsForWorkoutRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ExerciseID,
			&i.ExerciseSlug,
			&i.ExerciseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainingDays = `-- name: ListTrainingDays :many
select distinct local_date
from workout
where user_id = $1 and local_date <= $2
order by local_date desc
`

type ListTrainingDaysParams struct {
	UserID string
	Today  time.Time
}

// Los días (locales) en que el usuario entrenó, del más reciente al más
// viejo: la materia prima de la Brasa.
func (q *Queries) ListTrainingDays(ctx context.Context, arg ListTrainingDaysParams) ([]time.Time, error) {
	rows, err := q.db.Query(ctx, listTrainingDays, arg.UserID, arg.Today)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []time.Time
	for rows.Next() {
		var local_date time.Time
		if err := rows.Scan(&local_date); err != nil {
			return nil, err
		}
		items = append(items, local_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkouts = `-- name: ListWorkouts :many
select w.id, w.session_id, s.title as session_title,
       -- Una sesión suelta (sin Senda) no trae filas en la lateral: '' en
       -- vez de null, por lo mismo que en ListProgramProgress.
       coalesce(prog.slug, '')::text as program_slug,
       coalesce(prog.name, '')::text as program_name,
       w.started_at, w.finished_at, w.local_date
from workout w
join session s on s.id = w.session_id
left join lateral (
  select p.slug, p.name
  from program_session ps
  join program p on p.id = ps.program_id
  where ps.session_id = w.session_id
  order by p.id
  limit 1
) prog on true
where w.user_id = $1
  and ($2::bigint is null
       or (w.finished_at, w.id) < (select c.finished_at, c.id
                                     from workout c
                                    where c.user_id = $1 and c.id = $2))
order by w.finished_at desc, w.id desc
limit $3
`

type ListWorkoutsParams struct {
	UserID  string
	Before  *int64
	MaxRows int32
}

type ListWorkoutsRow struct {
	ID           int64
	SessionID    int64
	SessionTitle string
	ProgramSlug  string
	ProgramName  string
	StartedAt    time.Time
	FinishedAt   time.Time
	LocalDate    time.Time
}

// El historial del usuario, de lo más reciente a lo más viejo, con la Senda
// de cada sesión (la primera, si una sesión estuviera en varias).
//
// Paginación por cursor (keyset): la página siguiente pide "las anteriores
// al workout @before", el último que la app ya tiene. Se compara el par
// (finished_at, id) y no solo finished_at: dos Fraguas podrían terminar en
// el mismo instante, y el id desempata para que ninguna se repita ni se
// pierda entre páginas. A diferencia de offset ("saltear 40"), no se corre
// si entra una Fragua nueva mientras se pagina, y usa el índice
// workout_user_recent en vez de leer y descartar las filas salteadas.
//
// Si @before no es un workout del usuario, la subconsulta da null, la
// comparación también, y la página sale vacía.
func (q *Queries) ListWorkouts(ctx context.Context, arg ListWorkoutsParams) ([]ListWorkoutsRow, error) {
	rows, err := q.db.Query(ctx, listWorkouts, arg.UserID, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkoutsRow
	for rows.Next() {
		var i ListWorkoutsRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SessionTitle,
			&i.ProgramSlug,
			&i.ProgramName,
			&i.StartedAt,
			&i.FinishedAt,
			&i.LocalDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetProgramProgress = `-- name: ResetProgramProgress :exec
insert into program_reset (user_id, program_id, reset_at)
values ($1, $2, now())
on conflict (user_id, program_id) do update set reset_at = excluded.reset_at
`

type ResetProgramProgressParams struct {
	UserID    string
	ProgramID int64
}

// "Upsert": crea la fila, o si ya existe, actualiza la fecha.
func (q *Queries) ResetProgramProgress(ctx context.Context, arg ResetProgramProgressParams) error {
	_, err := q.db.Exec(ctx, resetProgramProgress, arg.UserID, arg.ProgramID)
	return err
}
